import type { Metadata } from "next";
import { Outfit, Roboto, Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/ui/navbar";

/* Fuentes para el texto */
const roboto = Roboto({
  subsets: ["latin"],
  weight:  ["400"],
  variable: "--font-roboto",
});

/* Fuente sans para la interfaz */
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${inter.variable}`}>
      <body className="bg-pixela-dark">
        <Navbar />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
